//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flash_It.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocaleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flash_It.Resources.LocaleResource", typeof(LocaleResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min battery level.
        /// </summary>
        internal static string BatterySaverPreferencesControl_MinLevel {
            get {
                return ResourceManager.GetString("BatterySaverPreferencesControl_MinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery saver.
        /// </summary>
        internal static string BatterySaverPreferencesControl_Title {
            get {
                return ResourceManager.GetString("BatterySaverPreferencesControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming call.
        /// </summary>
        internal static string CallPreferencesControl_Title {
            get {
                return ResourceManager.GetString("CallPreferencesControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string Miliseconds {
            get {
                return ResourceManager.GetString("Miliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off time.
        /// </summary>
        internal static string OffTime {
            get {
                return ResourceManager.GetString("OffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On time.
        /// </summary>
        internal static string OnTime {
            get {
                return ResourceManager.GetString("OnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of times.
        /// </summary>
        internal static string SmsPreferencesControl_NumberOfTimes {
            get {
                return ResourceManager.GetString("SmsPreferencesControl_NumberOfTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming text.
        /// </summary>
        internal static string SmsPreferencesControl_Title {
            get {
                return ResourceManager.GetString("SmsPreferencesControl_Title", resourceCulture);
            }
        }
    }
}
